services:
  # This is the container hosting our fastAPI
  web:
    build: ./fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app
      - ./ollama/pull-llama3.sh:/pull-llama3.sh
    networks:
      - tutorial-net
  # This container hosts our Ollama LLM and functionality
  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - tutorial-vol:/ollama
    networks:
      - tutorial-net
    # Run this command once in the box, pull ollama over
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]

networks:
  tutorial-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local